server:
  port: 8084
    
# My SQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BD_EDIDEMIO?serverTimezone=GMT-6
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
      
#  SQL #
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=Siscontrol
#    username: sa
#    password: 123456
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
 
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
# Spring Boot Admin
#  boot:
 #   admin:
 #     client:
 #       url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 15
      fetch-registry: true
      register-with-eureka: false 
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        